export const FAILURE = "FAILURE";
export const FIND_SALARY = "FIND_SALARY";

export const LOAD_SALARY_DETAIL = "LOAD_SALARY_DETAIL";
export const LOAD_SALARY_SUCCESS = "LOAD_SALARY_SUCCESS";

export const LOAD_POSITION_LISTING = "LOAD_POSITION_LISTING";
export const POSITION_LISTING_SUCCESS = "POSITION_LISTING_SUCCESS";
export const CHANGE_LANGUAGE= "CHANGE_LANGUAGE";
