const relatedJobs = {
    "Result": {
        "NumberFound": 7739,
        "NumberFoundDisplay": "5000+",
        "JobIndexStart": 1,
        "JobIndexEnd": 8,
        "PageNo": 1,
        "PageCount": 99,
        "ViewType": "b",
        "DetailViewUrl": "",
        "BriefViewUrl": "",
        "NativeFormatQuery": null,
        "NativeFormatResponse": null,
        "PageSize": 8,
        "ResultType": 0,
        "ErrorDetails": null,
        "LocationHints": [],
        "Jobs": [
            {
                "Date": "/Date(1582261200000)/",
                "IsBold": false,
                "Title": "Senior Software Engineer/ front end developer",
                "Company": "GDKN Corporation",
                "Location": "Boston, Massachusetts, 02210",
                "JobViewUrl": "https://job-openings.monster.com/senior-software-engineer-front-end-developer-boston-ma-us-gdkn-corporation/216102448",
                "Body": "Senior Software Engineer-Contact Center\n \n• The Senior Software Engineer at the Edge will have the chance to influence the decisions of a brand-new organization.\n• Software Engineers within the Edge team are trusted to own major parts of the codebas...",
                "SalaryPreciseFrom": 70,
                "SalaryPreciseTo": 73,
                "SalaryTimeMessageID": 2,
                "SalaryType": "2",
                "CurrencyISO": "USD",
                "JobBoardID": "1",
                "DateExpire": "/Date(-62135578800000)/",
                "Salary": "70.00+",
                "SalaryRange": "From 70.00 to 73.00 USD ",
                "CompanyXCode": "xgdknx",
                "RelevanceScore": 0.69,
                "CountryId": 164,
                "JobId": 216102448,
                "JobRefCode": "216102448",
                "JobApplyUrl": "https://job-openings.monster.com/senior-software-engineer-front-end-developer-boston-ma-us-gdkn-corporation/216102448",
                "IndustryId": 0,
                "CareerLevelMessageId": 0,
                "PhysicalCityName": "Boston",
                "PhysicalStateAbbr": "MA",
                "PhysicalCountryAbbr": "US",
                "PhysicalPostalCode": "02210",
                "PositionId": 19129308,
                "PostingID": null,
                "JobCategory": null,
                "CompanyConfidential": false,
                "Uuid": "7ec26b4e-e1a4-4f36-be02-9ae4a1704378",
                "Providername": null,
                "Providercode": null,
                "CompanyCode": null,
                "JobadpricingtypeID": 0,
                "MonsjobstatusID": 0,
                "MonsJobStatusIDList": null,
                "MonsoccID": 0,
                "MonsjoblevelID": 0,
                "MonslocationID": 0,
                "MonscategoryID": 0,
                "PScore": 0,
                "JobMapIndex": null,
                "Latitude": 42.346599999999995,
                "Longitude": -71.0403,
                "MescoID": 0,
                "MescoIDList": null,
                "MonsJobTypeID": 0,
                "MonsJobTypeIDList": null,
                "PostedDateString": "2020-02-21T12-00",
                "PostedDateMessage": "Posted 14 days ago"
            },
            {
                "Date": "/Date(1583125200000)/",
                "IsBold": false,
                "Title": "Cloud Engineer",
                "Company": "Fidelity TalentSource",
                "Location": "BOSTON, Massachusetts",
                "JobViewUrl": "https://job-openings.monster.com/cloud-engineer-boston-ma-us-fidelity-talentsource/e76446ae-019b-4101-8f4c-2c1623c20f0d",
                "Body": "Fidelity TalentSource is your destination for discovering your next temporary role at Fidelity Investments. We are currently sourcing for a Cloud Engineer to work in Fidelity’s Asset Management Technology in Boston, MA.\n\nWe are looking for a strong ...",
                "SalaryPreciseFrom": 0,
                "SalaryPreciseTo": 0,
                "SalaryTimeMessageID": 0,
                "SalaryType": "0",
                "CurrencyISO": "NA",
                "JobBoardID": "",
                "DateExpire": "/Date(-62135578800000)/",
                "Salary": "NA",
                "SalaryRange": "NA",
                "CompanyXCode": null,
                "RelevanceScore": 0.68,
                "CountryId": 164,
                "JobId": 160657,
                "JobRefCode": "160657",
                "JobApplyUrl": "https://jobs.veritude.com/#/jobs/160657?source=monster",
                "IndustryId": 0,
                "CareerLevelMessageId": 0,
                "PhysicalCityName": "BOSTON",
                "PhysicalStateAbbr": "MA",
                "PhysicalCountryAbbr": "US",
                "PhysicalPostalCode": "",
                "PositionId": 20269310,
                "PostingID": null,
                "JobCategory": null,
                "CompanyConfidential": false,
                "Uuid": "b288b969-92c6-4428-9856-8fd009e4489e",
                "Providername": null,
                "Providercode": null,
                "CompanyCode": null,
                "JobadpricingtypeID": 0,
                "MonsjobstatusID": 0,
                "MonsJobStatusIDList": null,
                "MonsoccID": 0,
                "MonsjoblevelID": 0,
                "MonslocationID": 0,
                "MonscategoryID": 0,
                "PScore": 0,
                "JobMapIndex": null,
                "Latitude": 42.358399999999989,
                "Longitude": -71.0598,
                "MescoID": 0,
                "MescoIDList": null,
                "MonsJobTypeID": 0,
                "MonsJobTypeIDList": null,
                "PostedDateString": "2020-03-02T12-00",
                "PostedDateMessage": "Posted 4 days ago"
            },
            {
                "Date": "/Date(1583384400000)/",
                "IsBold": false,
                "Title": "Sr. Full-Stack Software Engineer - Java, PHP, JS, React",
                "Company": "CyberCoders",
                "Location": "Newton, Massachusetts, 02459",
                "JobViewUrl": "https://job-openings.monster.com/sr-full-stack-software-engineer-java-php-js-react-newton-ma-us-cybercoders/216431783",
                "Body": "If you are a Sr. Full-Stack Software Engineer with experience, please read on!\n\n Located just in the suburbs of Boston, MA. We are rapidly growing at a rate of 50% a year! We are currently working in 20 states and expanding rapidly across the United...",
                "SalaryPreciseFrom": 120000,
                "SalaryPreciseTo": 175000,
                "SalaryTimeMessageID": 1,
                "SalaryType": "1",
                "CurrencyISO": "USD",
                "JobBoardID": "1",
                "DateExpire": "/Date(-62135578800000)/",
                "Salary": "120,000.00+",
                "SalaryRange": "From 120,000.00 to 175,000.00 USD manage jobs",
                "CompanyXCode": "xcyberc3x",
                "RelevanceScore": 0.67,
                "CountryId": 164,
                "JobId": 216431783,
                "JobRefCode": "216431783",
                "JobApplyUrl": "https://job-openings.monster.com/sr-full-stack-software-engineer-java-php-js-react-newton-ma-us-cybercoders/216431783",
                "IndustryId": 0,
                "CareerLevelMessageId": 0,
                "PhysicalCityName": "Newton",
                "PhysicalStateAbbr": "MA",
                "PhysicalCountryAbbr": "US",
                "PhysicalPostalCode": "02459",
                "PositionId": 21142588,
                "PostingID": null,
                "JobCategory": null,
                "CompanyConfidential": false,
                "Uuid": "c3a503dd-3fc1-4117-8c1c-3f329d27d4ef",
                "Providername": null,
                "Providercode": null,
                "CompanyCode": null,
                "JobadpricingtypeID": 0,
                "MonsjobstatusID": 0,
                "MonsJobStatusIDList": null,
                "MonsoccID": 0,
                "MonsjoblevelID": 0,
                "MonslocationID": 0,
                "MonscategoryID": 0,
                "PScore": 0,
                "JobMapIndex": null,
                "Latitude": 42.314600000000013,
                "Longitude": -71.1931,
                "MescoID": 0,
                "MescoIDList": null,
                "MonsJobTypeID": 0,
                "MonsJobTypeIDList": null,
                "PostedDateString": "2020-03-05T12-00",
                "PostedDateMessage": "Posted today"
            },
            {
                "Date": "/Date(1583298000000)/",
                "IsBold": false,
                "Title": "Senior Software Engineer",
                "Company": "GS Global Services Inc.",
                "Location": "boston, Massachusetts, 02108",
                "JobViewUrl": "https://job-openings.monster.com/senior-software-engineer-boston-ma-us-gs-global-services-inc/216405087",
                "Body": "Job Description\n\n \n\nOur client is one of the world's largest independent investment management firms. With US$1 trillion in assets under management, they serve as a trusted adviser to institutional clients and mutual fund sponsors in over 50 countri...",
                "SalaryPreciseFrom": 0,
                "SalaryPreciseTo": 0,
                "SalaryTimeMessageID": 1,
                "SalaryType": "1",
                "CurrencyISO": "NA",
                "JobBoardID": "1",
                "DateExpire": "/Date(-62135578800000)/",
                "Salary": "NA",
                "SalaryRange": "NA",
                "CompanyXCode": "xgsglobalx",
                "RelevanceScore": 0.67,
                "CountryId": 164,
                "JobId": 216405087,
                "JobRefCode": "216405087",
                "JobApplyUrl": "https://job-openings.monster.com/senior-software-engineer-boston-ma-us-gs-global-services-inc/216405087",
                "IndustryId": 0,
                "CareerLevelMessageId": 0,
                "PhysicalCityName": "boston",
                "PhysicalStateAbbr": "MA",
                "PhysicalCountryAbbr": "US",
                "PhysicalPostalCode": "02108",
                "PositionId": 21037089,
                "PostingID": null,
                "JobCategory": null,
                "CompanyConfidential": false,
                "Uuid": "36e2e338-b854-4bd0-b898-e3d81925e75f",
                "Providername": null,
                "Providercode": null,
                "CompanyCode": null,
                "JobadpricingtypeID": 0,
                "MonsjobstatusID": 0,
                "MonsJobStatusIDList": null,
                "MonsoccID": 0,
                "MonsjoblevelID": 0,
                "MonslocationID": 0,
                "MonscategoryID": 0,
                "PScore": 0,
                "JobMapIndex": null,
                "Latitude": 42.358100000000007,
                "Longitude": -71.0647,
                "MescoID": 0,
                "MescoIDList": null,
                "MonsJobTypeID": 0,
                "MonsJobTypeIDList": null,
                "PostedDateString": "2020-03-04T12-00",
                "PostedDateMessage": "Posted 1 day ago"
            },
            {
                "Date": "/Date(1583298000000)/",
                "IsBold": false,
                "Title": "Senior Software Engineer",
                "Company": "Mastech Digital",
                "Location": "Boston, Massachusetts, 02110",
                "JobViewUrl": "https://job-openings.monster.com/senior-software-engineer-boston-ma-us-mastech-digital/216411208",
                "Body": "Job Description: Mastech Digital provides digital and mainstream technology staff as well as Digital Transformation Services for leading American Corporations. We are currently seeking a Senior Software Engineer for our client in the Publishing doma...",
                "SalaryPreciseFrom": 0,
                "SalaryPreciseTo": 0,
                "SalaryTimeMessageID": 0,
                "SalaryType": "0",
                "CurrencyISO": "NA",
                "JobBoardID": "1,3902,6965",
                "DateExpire": "/Date(-62135578800000)/",
                "Salary": "NA",
                "SalaryRange": "NA",
                "CompanyXCode": "xmastech4x",
                "RelevanceScore": 0.67,
                "CountryId": 164,
                "JobId": 216411208,
                "JobRefCode": "216411208",
                "JobApplyUrl": "https://job-openings.monster.com/senior-software-engineer-boston-ma-us-mastech-digital/216411208",
                "IndustryId": 0,
                "CareerLevelMessageId": 0,
                "PhysicalCityName": "Boston",
                "PhysicalStateAbbr": "MA",
                "PhysicalCountryAbbr": "US",
                "PhysicalPostalCode": "02110",
                "PositionId": 21067220,
                "PostingID": null,
                "JobCategory": null,
                "CompanyConfidential": false,
                "Uuid": "79e18019-1b92-4960-a561-4fd2e944b83c",
                "Providername": null,
                "Providercode": null,
                "CompanyCode": null,
                "JobadpricingtypeID": 0,
                "MonsjobstatusID": 0,
                "MonsJobStatusIDList": null,
                "MonsoccID": 0,
                "MonsjoblevelID": 0,
                "MonslocationID": 0,
                "MonscategoryID": 0,
                "PScore": 0,
                "JobMapIndex": null,
                "Latitude": 42.356799999999993,
                "Longitude": -71.0536,
                "MescoID": 0,
                "MescoIDList": null,
                "MonsJobTypeID": 0,
                "MonsJobTypeIDList": null,
                "PostedDateString": "2020-03-04T12-00",
                "PostedDateMessage": "Posted 1 day ago"
            },
            {
                "Date": "/Date(1582866000000)/",
                "IsBold": false,
                "Title": "Software Engineer, C++",
                "Company": "Carbonite",
                "Location": "Boston, Massachusetts, 02111",
                "JobViewUrl": "https://job-openings.monster.com/software-engineer-c-boston-ma-us-carbonite/216302005",
                "Body": "Software Engineer, C++Job Label:WEBCAR-SoftwareEngineerC++2\n\n\n\n\nYou are an experienced C++ software engineer looking for an opportunity that offers challenging work and a highly visible impact on over one million users. You have established yourself...",
                "SalaryPreciseFrom": 0,
                "SalaryPreciseTo": 0,
                "SalaryTimeMessageID": 0,
                "SalaryType": "0",
                "CurrencyISO": "NA",
                "JobBoardID": "1,3902,6965",
                "DateExpire": "/Date(-62135578800000)/",
                "Salary": "NA",
                "SalaryRange": "NA",
                "CompanyXCode": "xaccolobusinessx",
                "RelevanceScore": 0.67,
                "CountryId": 164,
                "JobId": 216302005,
                "JobRefCode": "216302005",
                "JobApplyUrl": "https://job-openings.monster.com/software-engineer-c-boston-ma-us-carbonite/216302005",
                "IndustryId": 0,
                "CareerLevelMessageId": 0,
                "PhysicalCityName": "Boston",
                "PhysicalStateAbbr": "MA",
                "PhysicalCountryAbbr": "US",
                "PhysicalPostalCode": "02111",
                "PositionId": 19907083,
                "PostingID": null,
                "JobCategory": null,
                "CompanyConfidential": false,
                "Uuid": "e4b431b9-5577-41e7-9dd1-c3a0e8225f95",
                "Providername": null,
                "Providercode": null,
                "CompanyCode": null,
                "JobadpricingtypeID": 0,
                "MonsjobstatusID": 0,
                "MonsJobStatusIDList": null,
                "MonsoccID": 0,
                "MonsjoblevelID": 0,
                "MonslocationID": 0,
                "MonscategoryID": 0,
                "PScore": 0,
                "JobMapIndex": null,
                "Latitude": 42.351200000000006,
                "Longitude": -71.0614,
                "MescoID": 0,
                "MescoIDList": null,
                "MonsJobTypeID": 0,
                "MonsJobTypeIDList": null,
                "PostedDateString": "2020-02-28T12-00",
                "PostedDateMessage": "Posted 7 days ago"
            },
            {
                "Date": "/Date(1583384400000)/",
                "IsBold": false,
                "Title": "Senior Java Engineer",
                "Company": "Monster",
                "Location": "Weston, Massachusetts",
                "JobViewUrl": "https://job-openings.monster.com/senior-java-engineer-weston-ma-us-monster/215671819",
                "Body": "Senior Java Engineer \n\n\n\n\n\nOwn the Product!\n\nMonster Worldwide is seeking a talented Senior Java Engineer in our Weston, MA Headquarters to lead the design and implementation of Monster’s marketplace for either our Seeker and/or Employer platform.  ...",
                "SalaryPreciseFrom": 0,
                "SalaryPreciseTo": 0,
                "SalaryTimeMessageID": 0,
                "SalaryType": "0",
                "CurrencyISO": "NA",
                "JobBoardID": "1,3902,6965",
                "DateExpire": "/Date(-62135578800000)/",
                "Salary": "NA",
                "SalaryRange": "NA",
                "CompanyXCode": "xmonsterhires19x",
                "RelevanceScore": 0.67,
                "CountryId": 164,
                "JobId": 215671819,
                "JobRefCode": "215671819",
                "JobApplyUrl": "https://job-openings.monster.com/senior-java-engineer-weston-ma-us-monster/215671819",
                "IndustryId": 0,
                "CareerLevelMessageId": 0,
                "PhysicalCityName": "Weston",
                "PhysicalStateAbbr": "MA",
                "PhysicalCountryAbbr": "US",
                "PhysicalPostalCode": "",
                "PositionId": 17483419,
                "PostingID": null,
                "JobCategory": null,
                "CompanyConfidential": false,
                "Uuid": "eea6a80c-9b07-4e40-92e6-b0acbd449ec1",
                "Providername": null,
                "Providercode": null,
                "CompanyCode": null,
                "JobadpricingtypeID": 0,
                "MonsjobstatusID": 0,
                "MonsJobStatusIDList": null,
                "MonsoccID": 0,
                "MonsjoblevelID": 0,
                "MonslocationID": 0,
                "MonscategoryID": 0,
                "PScore": 0,
                "JobMapIndex": null,
                "Latitude": 42.366700000000009,
                "Longitude": -71.3032,
                "MescoID": 0,
                "MescoIDList": null,
                "MonsJobTypeID": 0,
                "MonsJobTypeIDList": null,
                "PostedDateString": "2020-03-05T12-00",
                "PostedDateMessage": "Posted today"
            },
            {
                "Date": "/Date(1582952400000)/",
                "IsBold": false,
                "Title": "Cloud Engineer",
                "Company": "The CEI Group, Inc.",
                "Location": "Framingham, Massachusetts, 01701",
                "JobViewUrl": "https://job-openings.monster.com/cloud-engineer-framingham-ma-us-the-cei-group-inc/210004902",
                "Body": "The Cloud Engineer will work collaboratively within the Cloud Engineering Department reporting to a team lead or manager. This is a key role and the ideal candidate will participate in engineering design initiatives across various disciplines of Clo...",
                "SalaryPreciseFrom": 135000,
                "SalaryPreciseTo": 165000,
                "SalaryTimeMessageID": 1,
                "SalaryType": "1",
                "CurrencyISO": "USD",
                "JobBoardID": "1",
                "DateExpire": "/Date(-62135578800000)/",
                "Salary": "135,000.00+",
                "SalaryRange": "From 135,000.00 to 165,000.00 USD manage jobs",
                "CompanyXCode": "xcompresx",
                "RelevanceScore": 0.67,
                "CountryId": 164,
                "JobId": 210004902,
                "JobRefCode": "210004902",
                "JobApplyUrl": "https://job-openings.monster.com/cloud-engineer-framingham-ma-us-the-cei-group-inc/210004902",
                "IndustryId": 0,
                "CareerLevelMessageId": 0,
                "PhysicalCityName": "Framingham",
                "PhysicalStateAbbr": "MA",
                "PhysicalCountryAbbr": "US",
                "PhysicalPostalCode": "01701",
                "PositionId": 1746380,
                "PostingID": null,
                "JobCategory": null,
                "CompanyConfidential": false,
                "Uuid": "ce1178ca-6bc4-4446-b2b3-70348cd54541",
                "Providername": null,
                "Providercode": null,
                "CompanyCode": null,
                "JobadpricingtypeID": 0,
                "MonsjobstatusID": 0,
                "MonsJobStatusIDList": null,
                "MonsoccID": 0,
                "MonsjoblevelID": 0,
                "MonslocationID": 0,
                "MonscategoryID": 0,
                "PScore": 0,
                "JobMapIndex": null,
                "Latitude": 42.3203,
                "Longitude": -71.4404,
                "MescoID": 0,
                "MescoIDList": null,
                "MonsJobTypeID": 0,
                "MonsJobTypeIDList": null,
                "PostedDateString": "2020-02-29T12-00",
                "PostedDateMessage": "Posted 6 days ago"
            }
        ],
        "SortOptions": [],
        "Pages": [
            {
                "Label": "1",
                "PageType": 0,
                "IsActive": true,
                "Url": "index.aspx?q=Software+Developer+%2f+Engineer&where=Boston%2c+MA&stp=ScoreFenceMain&sort=rv&pdif=-1&cy=US&pg=1",
                "Number": 1
            },
            {
                "Label": "2",
                "PageType": 0,
                "IsActive": false,
                "Url": "index.aspx?q=Software+Developer+%2f+Engineer&where=Boston%2c+MA&stp=ScoreFenceMain&sort=rv&pdif=-1&cy=US&pg=2",
                "Number": 2
            },
            {
                "Label": "3",
                "PageType": 0,
                "IsActive": false,
                "Url": "index.aspx?q=Software+Developer+%2f+Engineer&where=Boston%2c+MA&stp=ScoreFenceMain&sort=rv&pdif=-1&cy=US&pg=3",
                "Number": 3
            },
            {
                "Label": "4",
                "PageType": 0,
                "IsActive": false,
                "Url": "index.aspx?q=Software+Developer+%2f+Engineer&where=Boston%2c+MA&stp=ScoreFenceMain&sort=rv&pdif=-1&cy=US&pg=4",
                "Number": 4
            },
            {
                "Label": "5",
                "PageType": 0,
                "IsActive": false,
                "Url": "index.aspx?q=Software+Developer+%2f+Engineer&where=Boston%2c+MA&stp=ScoreFenceMain&sort=rv&pdif=-1&cy=US&pg=5",
                "Number": 5
            },
            {
                "Label": "6",
                "PageType": 0,
                "IsActive": false,
                "Url": "index.aspx?q=Software+Developer+%2f+Engineer&where=Boston%2c+MA&stp=ScoreFenceMain&sort=rv&pdif=-1&cy=US&pg=6",
                "Number": 6
            },
            {
                "Label": "...",
                "PageType": 3,
                "IsActive": false,
                "Url": null,
                "Number": -1
            },
            {
                "Label": "99",
                "PageType": 0,
                "IsActive": false,
                "Url": "index.aspx?q=Software+Developer+%2f+Engineer&where=Boston%2c+MA&stp=ScoreFenceMain&sort=rv&pdif=-1&cy=US&pg=99",
                "Number": 99
            },
            {
                "Label": ">",
                "PageType": 2,
                "IsActive": false,
                "Url": "index.aspx?q=Software+Developer+%2f+Engineer&where=Boston%2c+MA&stp=ScoreFenceMain&sort=rv&pdif=-1&cy=US&pg=2",
                "Number": 2
            }
        ],
        "WantedJobs": [],
        "WantedFacets": [],
        "FilterFields": [],
        "RelatedJobTitles": [],
        "JobFacets": [],
        "SortOder": "rv",
        "FilterFound": 0,
        "ClearAllFiltersUrl": null,
        "JobsMapData": null,
        "ResumeTitles": "",
        "QueryString": "q=Software+Developer+%2f+Engineer&where=Boston%2c+MA&stp=ScoreFenceMain&sort=rv&pdif=-1&cy=US",
        "Country": "US"
    },
    "Status": "Success",
    "ErrorDetails": "Success"
}

export default relatedJobs